# Generated by Django 6.0.7 on 2026-07-14 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_key', models.CharField(max_length=150, unique=True)),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Forecast Cache',
                'verbose_name_plural': 'Forecast Caches',
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_key', models.CharField(max_length=150, unique=True)),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Weather Cache',
                'verbose_name_plural': 'Weather Caches',
            },
        ),
    ]
